// @ts-check
// Nuxt-aware base config is generated by the @nuxt/eslint module.
import withNuxt from './.nuxt/eslint.config.mjs'
import nuxtUiV4Compat from './eslint-plugins/nuxt-ui-v4-compat.mjs'

export default withNuxt(
  {
    ignores: [
      '**/.nuxt/**',
      '**/.output/**',
      '**/.nitro/**',
      '**/node_modules/**',
      '**/.tmp-post-edit-hook-*/**',
      '**/public/search-index.json',
      '**/content/**/*.json',
      '**/docs/design_handoff_dwselect_redesign/**',
      '**/test-results/**',
      '**/playwright-report/**',
    ],
  },
  {
    files: ['**/*.{js,mjs,ts,vue}'],
    rules: {
      '@stylistic/quotes': ['error', 'single', { avoidEscape: true }],
      '@stylistic/semi': ['error', 'never'],
      '@stylistic/indent': ['error', 2],
      '@stylistic/comma-dangle': ['error', 'always-multiline'],
      '@stylistic/arrow-parens': ['error', 'always'],
      '@stylistic/no-tabs': 'off',
      '@stylistic/quote-props': ['error', 'as-needed'],
      '@typescript-eslint/no-unused-vars': [
        'error',
        {
          argsIgnorePattern: '^_',
          varsIgnorePattern: '^_',
          caughtErrorsIgnorePattern: '^_',
        },
      ],
    },
  },
  {
    files: ['**/*.vue'],
    plugins: {
      'nuxt-ui-v4-compat': nuxtUiV4Compat,
    },
    rules: {
      'vue/max-attributes-per-line': 'off',
      'vue/prop-name-casing': 'off',
      'nuxt-ui-v4-compat/no-deprecated-options-prop': 'error',
      'nuxt-ui-v4-compat/no-deprecated-option-attribute': 'error',
      'nuxt-ui-v4-compat/no-deprecated-value-attribute': 'error',
      'nuxt-ui-v4-compat/no-renamed-components': 'error',
      'nuxt-ui-v4-compat/no-nullify-modifier': 'error',
      'nuxt-ui-v4-compat/no-deprecated-color-prop': 'error',
      'nuxt-ui-v4-compat/no-deprecated-wrapper-ui-slot': 'error',
      'nuxt-ui-v4-compat/no-deprecated-click-in-items': 'error',
    },
  },
)
